# TODO: Add testing

pipeline:
  docker_build:
    image: plugins/docker
    auto_tag: true
    repo: docker.netsoc.co/crnlpanic/nocturne
    registry: docker.netsoc.co
    build_args:
      - SECRET_KEY=$SECRET_KEY
    secrets: [docker_username, docker_password]
    when:
      event: [push, tag]
      branch: master
